services:
  - type: web
    name: tasrod
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn main:app"
    envVars:
      - key: FLASK_ENV
        value: production
